@startuml

class Supplier {
  - name()
  - food() 
  - profit()
  - sell()
  _construct()
  get_Supplier_name()
  get_Supplier_food()
  get_Supplier_profit()
  get_Supplier_sell()
}

class Distributor extends Supplier {
  - name()
  - foodOrdered()
  + foodSold()
  - profit()
  _construct()
  get_Distributor_name()
  get_Distributor_foodOrdered()
  get_Distributor_foodSold()
  get_profit()
}

class Food {
  - foodType()
  - cost()
  - distributor()
  _construct()
  get_Food_foodType()
  get_Food_cost()
  get_Food_distributor()
}




Supplier --|> Distributor : sells to
Distributor --|> Customer : sells to
@enduml